r314: Remove the mod_auth_vas_module alias
As far as I can tell it does nothing, except cause compilation failure
on HPUX with:
> error: alias definitions not supported in this configuration

Fixes bug #463